version: '3'

services:
  zookeeper-1:
    container_name: zookeeper-1
    image: confluentinc/cp-zookeeper:5.0.0
    volumes:
      - $PWD/kafka/zookeeper-1/data:/var/lib/zookeeper/data
      - $PWD/kafka/zookeeper-1/txn-logs:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=22181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  zookeeper-2:
    container_name: zookeeper-2
    image: confluentinc/cp-zookeeper:5.0.0
    volumes:
      - $PWD/kafka/zookeeper-2/data:/var/lib/zookeeper/data
      - $PWD/kafka/zookeeper-2/txn-logs:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  zookeeper-3:
    container_name: zookeeper-3
    image: confluentinc/cp-zookeeper:5.0.0
    volumes:
      - $PWD/kafka/zookeeper-3/data:/var/lib/zookeeper/data
      - $PWD/kafka/zookeeper-3/txn-logs:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_CLIENT_PORT=42181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  kafka-1:
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: kafka-1
    image: confluentinc/cp-kafka:5.0.0
    volumes:
      - $PWD/kafka/kafka-1/data:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:29092
  kafka-2:
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: kafka-2
    image: confluentinc/cp-kafka:5.0.0
    volumes:
      - $PWD/kafka/kafka-2/data:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:39092
  kafka-3:
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    container_name: kafka-3
    image: confluentinc/cp-kafka:5.0.0
    volumes:
      - $PWD/kafka/kafka-3/data:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:49092